build:
    tests:
        override:
            -
                command: 'npm run jest'
                coverage:
                    file: 'coverage/clover.xml'
                    format: 'clover'

filter:
    excluded_paths:
        - "__tests__"
        - "__mocks__"
        - "coverage"
        - "dist"
        - "docker"
        - "node_modules"
